

-- put cursor her then click execute

--DELETE TABLE
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS ACCOUNT_TRANSACTION;
DROP TABLE IF EXISTS BILLPAYMENT
DROP TABLE IF EXISTS CHEQUE
DROP TABLE IF EXISTS CUSTOMER
DROP TABLE IF EXISTS LOAN_SERVICE
DROP TABLE IF EXISTS PERSONNEL
DROP TABLE IF EXISTS SERVICE